### ISSUE TITLE
Mor.homework_3

### ISSUE THREAD

**Issue by Sv-mor-79** [WEB-road/Morozova-homework3#1]
please check my homework

**Comment by Appof** [comment]
1.  Багато елементів div, вони просто збільшують код і складність читання(https://github.com/WEB-road/Morozova-homework3/blob/1510d56fd4bac78bf4abb0047b985fd14411ed9c/index.html#L9-L25)
2.  Пустий тег? (https://github.com/WEB-road/Morozova-homework3/blob/1510d56fd4bac78bf4abb0047b985fd14411ed9c/index.html#L22)
3.  Слідкуйте за вкладеністю тегів. Поганий приклад: (https://github.com/WEB-road/Morozova-homework3/blob/1510d56fd4bac78bf4abb0047b985fd14411ed9c/index.html#L11-L15) _PS Пусті теги і вкладеність тегів пофіксити по всьому проекті._
4. Тут немає навігації (https://github.com/WEB-road/Morozova-homework3/blob/1510d56fd4bac78bf4abb0047b985fd14411ed9c/index.html#L117)
5. Навігації повинна бути посиланнями -  не текстом (https://github.com/WEB-road/Morozova-homework3/blob/1510d56fd4bac78bf4abb0047b985fd14411ed9c/index.html#L134-L140)

**Comment by Appof** [comment]
6. outline краще не прибирати, скрін рідери визначають по ньому положення курсору https://github.com/WEB-road/Morozova-homework3/blob/1510d56fd4bac78bf4abb0047b985fd14411ed9c/css/style.css#L12-L13
7. Ці елементи по дефолту блочні https://github.com/WEB-road/Morozova-homework3/blob/1510d56fd4bac78bf4abb0047b985fd14411ed9c/css/style.css#L15
8.  font-size двічі https://github.com/WEB-road/Morozova-homework3/blob/1510d56fd4bac78bf4abb0047b985fd14411ed9c/css/style.css#L20-L22
9. Слеш? https://github.com/WEB-road/Morozova-homework3/blob/1510d56fd4bac78bf4abb0047b985fd14411ed9c/css/style.css#L62
10.  Дублювання коду треба уникати, дані встативсоті наслідуються, тому їх можна вказати раз https://github.com/WEB-road/Morozova-homework3/blob/1510d56fd4bac78bf4abb0047b985fd14411ed9c/css/style.css#L74-L75
https://github.com/WEB-road/Morozova-homework3/blob/1510d56fd4bac78bf4abb0047b985fd14411ed9c/css/style.css#L80-L81
11. Вважається поганою практикою робити фіксовану висоту блоку, якщо в середені нього є контент. Це може зламати верстку. https://github.com/WEB-road/Morozova-homework3/blob/1510d56fd4bac78bf4abb0047b985fd14411ed9c/css/style.css#L97
12.  Слеш? https://github.com/WEB-road/Morozova-homework3/blob/1510d56fd4bac78bf4abb0047b985fd14411ed9c/css/style.css#L274
https://github.com/WEB-road/Morozova-homework3/blob/1510d56fd4bac78bf4abb0047b985fd14411ed9c/css/style.css#L288
https://github.com/WEB-road/Morozova-homework3/blob/1510d56fd4bac78bf4abb0047b985fd14411ed9c/css/style.css#L299

**Comment by Appof** [comment]
- Табуляції коду, відступи між тегами, вкледність тегів - це важливі пункти при стовренні сайту. Вони підвищують читабельність коду та його охайність. Невже ви не бачили прикладів на відео як прийнято писати html код? https://github.com/WEB-road/Morozova-homework3/blob/2e6b934cdf2f7fd3e20a109c193569ff0ea0c038/index.html#L10-L17
- body не флекс елемент. https://github.com/WEB-road/Morozova-homework3/blob/2e6b934cdf2f7fd3e20a109c193569ff0ea0c038/css/style.css#L57
- По замовчуванню блоки розміщуються в ряд, це ще називають стандартним потоком документу. Цей клас є лишнім.https://github.com/WEB-road/Morozova-homework3/blob/2e6b934cdf2f7fd3e20a109c193569ff0ea0c038/css/style.css#L81-L84
- Не відповідає зовнішньому вигляду на макеті https://github.com/WEB-road/Morozova-homework3/blob/2e6b934cdf2f7fd3e20a109c193569ff0ea0c038/index.html#L88-L92
- Навігація в футері має інший колір https://github.com/WEB-road/Morozova-homework3/blob/2e6b934cdf2f7fd3e20a109c193569ff0ea0c038/index.html#L105-L111
- **Відсутній контейнер, контент не відцентрований**. Відцентовувати і обмежити контент потрібно div елементом з css властивостями, а не властивістю `margin ` до всіх елементів. Перечитати і пройти матеріал про контейнер
- Це не посилання,  а просто текст з імейлом https://github.com/WEB-road/Morozova-homework3/blob/2e6b934cdf2f7fd3e20a109c193569ff0ea0c038/index.html#L97-L100
-  Не забувайте вішати асайн на мене після того як запушили домашку. **_І перед тим як пушити, переконайтесь що ви виправили всі пункти до яких були зауваження_**
